[package]
name = "hop"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0"
clap = "2"
ansi_term = "0.12"


[dev-dependencies]
assert_cmd = "2"
predicates = "2"
tempfile = "3"
